[project]
name = "anime-from-terminal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "iterfzf>=1.8.0.62.0",
    "requests>=2.32.5",
]
